### ISSUE TITLE
生成的电子书永远只有三页，不能用

### ISSUE THREAD

**Issue by xiangxianzhang** [YaoZeyuan/ZhihuHelp#103]
生成的电子书有错误，只有三页，并且提示
“This page contains the following errors:
error on line 47 at column 11: Opening and ending tag mismatch: br line 0 and div
Below is a rendering of the page up to the first error.”

摘录来自: ZhihuHelp1.8.0. “知乎问题(40377156)答案集”。 iBooks.

**Comment by duhai973** [comment]
正在使用，没有问题

**Comment by YaoZeyuan** [comment]
因为你是用iBook打开的，用 多看阅读 就没有问题了
