### ISSUE TITLE
多线程处理异常，数据堆栈错误

### ISSUE THREAD

**Issue by wosyem** [YaoZeyuan/ZhihuHelp#24]
http://www.zhihu.com/people/wheeler

http://www.zhihu.com/people/emily-lou

抓取这两人时出现的问题，默认帐号，设定，图片1

**Comment by YaoZeyuan** [comment]
感谢反馈，新版里面已经没有这个问题了：）

**Comment by wosyem** [comment]
那是什么原因造成的呢,我看过你的code,无奈水平不够没发现问题..

**Comment by YaoZeyuan** [comment]
嗯，感觉像是知乎的服务器有问题，抓取的时候一直报socket.error错误，Http模块没捕获到，程序就崩了- -

新版本已经把这个问题解决掉了：）
