### ISSUE TITLE
epub在多看下缺少段落

### ISSUE THREAD

**Issue by zihanhuang** [YaoZeyuan/zhihuhelp#25]
多发生在图片附近。比如这篇
https://zhuanlan.zhihu.com/p/20581737

在多看下，“对，小白，姜小白。”后面就是“可是齐国也确实做到了“尊王攘夷……”。中间的段落都看不到。用edge查看是正常的。
可能是多看的问题？

**Comment by YaoZeyuan** [comment]
验证了下, 手机上用QQ浏览器打开正常, 用电脑看也正常, 只有多看异常

我查了下html源代码, 应该是知乎提供的html有问题, 内容跑到标签外边了, 导致多看识别失败, 展示不出来

这个改不了, 节哀...
