### ISSUE TITLE
能否支持只拉取指定数量的回答

### ISSUE THREAD

**Issue by kollyQAQ** [YaoZeyuan/zhihuhelp#27]
因为有些问题的回答数特别多，四五千都有，执行时间爆炸，所以能否提供一个参数只拉取指定数量的回答，配置按照点赞数降序排列，达到类似只看点赞前 50 的回答这种需求

感谢

**Comment by YaoZeyuan** [comment]
这种编程实现起来太麻烦了, 暂不考虑哈
