### ISSUE TITLE
非专栏内的文章id获取不了

### ISSUE THREAD

**Issue by luciaziyi** [YaoZeyuan/zhihuhelp#34]
个人页主页，非专栏内的文章集合，网址为https://www.zhihu.com/people/XXX/posts
该网址无法识别出id。

现有的文章摘取https://zhuanlan.zhihu.com/p/58653502 是一个专栏内的一篇文章。

**Comment by YaoZeyuan** [comment]
该功能已添加, 为"用户发布的所有文章"
