### ISSUE TITLE
希望能限定某个话题下的回答数量，感谢

### ISSUE THREAD

**Issue by rajesh942** [YaoZeyuan/zhihuhelp#35]
问题：有些话题动则几万个回答，执行任务经常失败，生成的问题几百M，放到阅读器里加载很慢

建议：能让我们配置，仅展示某个话题下点赞数前**100**的回答。类似于知乎web端官方话题下的精选排序方式，只是做个数量筛选。参考：https://www.zhihu.com/topic/19550560/top-answers

十分感激，若体验好，愿意向翻墙软件一样，每月付费订阅使用

**Comment by YaoZeyuan** [comment]
话题下的回答是精选回答, 最多1000个

如果量太大可以考虑使用分卷功能, 每100个回答一卷, 也能解决问题
