### ISSUE TITLE
网页标签不配对

### ISSUE THREAD

**Issue by liuxilu** [YaoZeyuan/zhihuhelp#38]
请看图 https://pic3.zhimg.com/80/v2-1c4124e07f473591d48b654ca27d8945_hd.png

**Comment by liuxilu** [comment]
不好意思放错图了 https://pic3.zhimg.com/80/v2-1c4124e07f473591d48b654ca27d8945_hd.png

**Comment by liuxilu** [comment]
那两个<br>

**Comment by YaoZeyuan** [comment]
嗯, 这个是知乎自身html的bug

我替换下

**Comment by YaoZeyuan** [comment]
已修改
