### ISSUE TITLE
总是无法登陆啊, 无论内置帐号, 还是自己输入的帐号. 无限循环在输入验证码过程中

### ISSUE THREAD

**Issue by remerci** [YaoZeyuan/ZhihuHelp#52]

**Comment by knarfeh** [comment]
不知道你登陆上没有，我刚试了一下，在Windows 7下可以登陆：
![loginsu](https://cloud.githubusercontent.com/assets/6964284/12372753/cd7552ac-bc9c-11e5-85f2-d3bcf783d085.png)
在MacMac 下也可以登陆：
<img width="587" alt="login_success" src="https://cloud.githubusercontent.com/assets/6964284/12372762/15904e98-bc9d-11e5-97c1-e041c6bb9804.png">

**Comment by YaoZeyuan** [comment]
重新下一个试试？
如果不行的话可以加我QQ，547320073，我们远程协助看下
