### ISSUE TITLE
修正回答日期抓取错误的bug

### ISSUE THREAD

**Issue by YaoZeyuan** [YaoZeyuan/ZhihuHelp#53]
目前的Parser里分析回答日期时还是有bug，待改正
另外就是赶快把外包项目结束了吧。。。年都快要过不好了- -

**Comment by knarfeh** [comment]
能不能具体一点啊。。。截个图啥的。。

**Comment by YaoZeyuan** [comment]
比如用户回答集锦中，收集到的用户回答日期全都是2000-01-01；在问题集锦中，直接收集不到回答日期(日期显示为1357-08-12)。

我晚上回家看看。

![示例](https://cloud.githubusercontent.com/assets/7150325/12406792/58d703b4-be8b-11e5-9240-4e6892ed2a44.png)

**Comment by YaoZeyuan** [comment]
怀疑是测试时知乎本身页面结构不统一导致的，现在已经无法重现该bug了
