### ISSUE TITLE
现在程序无法运行了吗？特来看看……然后看到了“因法律问题……”

### ISSUE THREAD

**Issue by gdd111** [YaoZeyuan/zhihuhelp#55]
【已解决】

**Comment by wang-y-z** [comment]
怎么解决的呀

**Comment by lingr7** [comment]
我估计是源码依然正常，只不过要自己构建编译环境，不懂前端，不知道这个叫不叫编译，反正要运行程序就得自己折腾一下。

**Comment by lingr7** [comment]
10月的时候，微博私信问过作者，作者说是知乎的接口验证方案改了，所以现在（10月）构建新版本也无法抓取知乎信息了。
