### ISSUE TITLE
1.7.4版本bug

### ISSUE THREAD

**Issue by biubiuboom** [YaoZeyuan/ZhihuHelp#67]
之前记住的登录账户，再次使用时输入任意键回车取消旧设置。
然后使用内置账号登陆时（要求直接回车），回车后却使用了上次记住的账号登陆。

**Comment by biubiuboom** [comment]
抓取问题回答时，没有按回答数分卷。
epub目录只显示：(1)(1)
epub页眉是显示问题的，但带了奇怪的后缀（我猜1是第一卷卷标序号吧）：)_(1)
估计也是这个问题导致。
感谢作者的工作！

**Comment by YaoZeyuan** [comment]
ok，我晚上回来修下：）

**Comment by duhai973** [comment]
1.7.4在解析页面结束后闪退

**Comment by YaoZeyuan** [comment]
已修复
