### ISSUE TITLE
标题中带特殊字符，iBooks无法打开

### ISSUE THREAD

**Issue by knarfeh** [YaoZeyuan/ZhihuHelp#73]
在爬取 http://zhuanlan.zhihu.com/jimmychow 的过程中，发现如果标题中带有特殊字符，iBooks是无法打开的，比如 http://zhuanlan.zhihu.com/jimmychow 这个专栏，标题中有&符号（其实问题，回答类型也是如此）。

**Comment by YaoZeyuan** [comment]
我加了一个修复文件名的函数，自动替换掉非法文字，现在可以了
