### ISSUE TITLE
epub文件中缺少dc:language字段

### ISSUE THREAD

**Issue by Arthur-Feng** [YaoZeyuan/ZhihuHelp#77]
用kindlegen转换生成的epub文件时提示：

> 错误(prcgen):E23005: 元数据中没有指定语言。dc:Language 字段为必填项。异常终止。

查看生成的epub文件中的content.opf，其中metadata中缺少dc:language字段，可以考虑加上以下字段：
`<dc:language>zh</dc:language>`，标明文件语言。

更好的是在配置文件中加入一项配置指定文件语言，默认为中文。因为在kindle中，只能使用文件指定语言的字典，对于外语较多的文件手动指定为其他语言以方便使用字典。

**Comment by knarfeh** [comment]
感谢反馈，已经添加了dc:language字段，默认是中文。用kindlegen试了一下，尽管warning信息比较多，但可以用kindlegen转mobi格式了！  

已经Pull requests了，就等 YaoZeyuan 同学 check 代码了。解决了这个问题，用kindlegen转mobi就很方便了，对kindle原生系统用户来说也是福音，再次感谢 @Arthur-Feng 同学的反馈。

突然想到，在配置文件中加入一项配置指定语言没有太大必要，毕竟知乎网是中文问答社区...
