### ISSUE TITLE
1.7.3.11无法使用内置账号

### ISSUE THREAD

**Issue by firstrose** [YaoZeyuan/ZhihuHelp#81]
直接要求输入账号

**Comment by joint-song** [comment]
直接回车还是要求输入账号
+1

**Comment by joint-song** [comment]
哦，刚看到一个comment，https://github.com/YaoZeyuan/ZhihuHelp/commit/fb57c690387ef9b3478978122c457c7367a02abf，这个close掉吧

**Comment by YaoZeyuan** [comment]
新版已经可以了
