### ISSUE TITLE
抓取量大会触发验证码，希望能调整抓取速度

### ISSUE THREAD

**Issue by zhuxiaochen1990** [YaoZeyuan/ZhihuHelp#84]
抓的答案多了就会要输入验证码，导致不能继续，然后跳出程序。
可以改进下抓取速度，试试看能不能避免跳出

**Comment by YaoZeyuan** [comment]
现在改成模拟客户端了，而且。。。说真的速度也挺慢的(抓取的时候没有多线程)，这回应该没问题了
