### ISSUE TITLE
文章中含有代码块的地方格式会崩

### ISSUE THREAD

**Issue by leon-woo** [YaoZeyuan/ZhihuHelp#86]
![image](https://cloud.githubusercontent.com/assets/22760977/19259055/8d76cdec-8fb0-11e6-8ed6-0564cb35819d.png)

![image](https://cloud.githubusercontent.com/assets/22760977/19259064/a9e9e19e-8fb0-11e6-9a21-66dc5a37cedc.png)

**Comment by YaoZeyuan** [comment]
问题已修复：）
