### ISSUE TITLE
有的回答无图片

### ISSUE THREAD

**Issue by duhai973** [YaoZeyuan/ZhihuHelp#88]
我看html文件中

- > class="content_image"这种无图片

- >class="duokan-image-single"这种有图片

**Comment by duhai973** [comment]
而在imagine文件夹里是有这个图片，不过文件名不对

**Comment by duhai973** [comment]
在1.7.3.1和1.7.4中均有这种情况出现

**Comment by duhai973** [comment]
同时我尝试把图片质量改为2，也会出现同样情况

**Comment by duhai973** [comment]
如果单独把回答链接制作电子书则有图片

**Comment by duhai973** [comment]
问题可以复现，而且没有图片的回答一样
图片池里有图片，但是没有写入到html和epub中去

**Comment by YaoZeyuan** [comment]
现在应该没有这个问题了吧
