### ISSUE TITLE
在这个收藏夹里在收集问题的时候会退出

### ISSUE THREAD

**Issue by duhai973** [YaoZeyuan/ZhihuHelp#90]
收藏夹为https://www.zhihu.com/collection/19655399
好像是没获取到data什么的
万万没想到作者居然还更新了（*-*） @YaoZeyuan

**Comment by YaoZeyuan** [comment]
这是因为知乎已经把问题删除了，但是收藏夹接口里的数据没有同步删除导致的。需要在获取问题数据时单独再处理下

我记下来，等回家改改吧：）

**Comment by YaoZeyuan** [comment]
已修复
